// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertChirp = `-- name: InsertChirp :one
INSERT INTO chirp (id, body, user_id, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    NOW(),
    NOW()
)
RETURNING id, created_at, updated_at, body, user_id
`

type InsertChirpParams struct {
	ID     uuid.UUID
	Body   string
	UserID uuid.UUID
}

func (q *Queries) InsertChirp(ctx context.Context, arg InsertChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, insertChirp, arg.ID, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
